# Generated by Django 4.1.4 on 2022-12-09 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
